# ansible-playbook PBX.yml

- name : Echo all of the ansible servers
  hosts: "*"
  tasks:
   - name: Echo
     #shell: echo "connected"
     shell: asterisk -rx 'iax2 show peers' && asterisk -rx 'core show channels' && asterisk -rx 'sip show peers' | grep call
     
     register: command_output
   
   - debug: 
            var: command_output.stdout_lines
