# ansible-playbook PBX.yml

- name : Echo all of the ansible servers
  hosts: "*"
  tasks:
   - name: Echo
     shell: echo "connected"
     register: command_output
   
   - debug: 
            var: command_output.stdout_lines
