# ansible-playbook PBX.yml

- name : Echo all of the ansible servers
  hosts: "*"
  tasks:
   - name: Echo
     #shell: echo "connected"
     shell: rasterisk -x  "core show channels verbose"
     
     register: command_output
   
   - debug: 
            var: command_output.stdout_lines
