# ansible-playbook LinuxUpdate.yml

- name : update all linux servers using yum
  hosts: "*"
  tasks:
   - name: upgrade the phone servers
     shell: yum update -y && yum upgrade -y
     register: yumUpdateUpgrade_output
     
     - debug:
           var: yumUpdateUpgrade_output.stdout_lines
           
   - name: update all linux servers using apt
     shell: apt-get update -y && apt-get upgrade -y
     register: aptUpdateUpgrade_output
     
     - debug:
           var: aptUpdateUpgrade_output.stdout_lines
  
