# ansible-playbook PBX.yml

- name : update the phone servers on all clients
  hosts: "*"
  tasks: 
   - name: upgrade the phone servers
     win_command: start chrome /incognito https://www.youtube.com/watch?v=dQw4w9WgXcQ #fwconsole ma upgradeall 
#     register: upgrade_output     
     
#   - debug: 
 #        var: upgrade_output.stdout_lines
          
          
 #  - name: reload the fw console
#     shell: fwconsole reload
 #    register: reload_output
     
 #  - debug: 
      #      var: reload_output.stdout_lines
     
     
     #- name : Reboots system
      # hosts: "*"
       #tasks:
       #- name: reboot the system
        # shell: reboot
          
          
