---
# ansible-playbook PBX.yml

- name : update the phone servers on all clients
  hosts: all
  tasks: 
   -name: upgrade the phone servers
    shell: fwconsole ma upgradeall
          
   -name: reload the fw console
    shell: fwconsole reload
          
   -name: reboot the system
    shell: reboot
          
          
