---
# ansible-playbook test.yml

- name: speak
  hosts: "*"   
  tasks:
   - name: Install all updates and reboot as many times as needed
     ansible.windows.win_updates:
       category_names: '*'
       reboot: yes
     
     
 # - name:
      #  win_command: cmd.exe /c mkdir C:\Users\samuel\Desktop\Testing_Ansible
#   - name: speak
    # win_command:  PowerShell -Command "Add-Type -AssemblyName System.Speech; (New-Object System.Speech.Synthesis.SpeechSynthesizer).Speak('ansible, connected');"
