---
# ansible-playbook test.yml

- name: Install windows updates
  hosts: "*"
  tasks:      
   - name: Install windows updates
     win_command:  PowerShell -Command "Add-Type -AssemblyName System.Speech; (New-Object System.Speech.Synthesis.SpeechSynthesizer).Speak('Feet off of the table');"
     
 #    win_updates:
   #    catagory_names:
 #            - CriticalUpdates
   #         - SecurityUpdates
   #          - UpdateRollups
     #  reboot: yes
    #   reboot_timeout: 360
     
     
 # - name:
      #  win_command: cmd.exe /c mkdir C:\Users\samuel\Desktop\Testing_Ansible
