---
# ansible-playbook test.yml

- name: speak
  hosts: "*"   
  tasks:
   ansible.windows.win_updates:
    catagory_names:
           - CriticalUpdates
           - SecurityUpdates
           - UpdateRollups
    reboot: yes
    reboot_timeout: 360
     
     
 # - name:
      #  win_command: cmd.exe /c mkdir C:\Users\samuel\Desktop\Testing_Ansible
#   - name: speak
    # win_command:  PowerShell -Command "Add-Type -AssemblyName System.Speech; (New-Object System.Speech.Synthesis.SpeechSynthesizer).Speak('ansible, connected');"
