---
- hosts: "*"
  tasks:
  - name: Choose which Windows updates to install
    win_updates:
        category_names: CriticalUpdates;SecurityUpdates; UpdateRollups;
        reboot: yes
        register: installed_update_count
        log_path: C:\ansible.install.txt
     
 # - name:
      #  win_command: cmd.exe /c mkdir C:\Users\samuel\Desktop\Testing_Ansible
#   - name: speak
    # win_command:  PowerShell -Command "Add-Type -AssemblyName System.Speech; (New-Object System.Speech.Synthesis.SpeechSynthesizer).Speak('ansible, connected');"
