---
- hosts: "*"
  tasks:
  - name: Choose which Windows updates to install
    win_updates:
        category_names: CriticalUpdates;
        reboot: yes
  - debug: 
         var: installed_update_count
     
 # - name:
      #  win_command: cmd.exe /c mkdir C:\Users\samuel\Desktop\Testing_Ansible
#   - name: speak
    # win_command:  PowerShell -Command "Add-Type -AssemblyName System.Speech; (New-Object System.Speech.Synthesis.SpeechSynthesizer).Speak('ansible, connected');"
