---
# ansible-playbook test.yml

- name: Install windows updates
  hosts: "*"
  tasks:
      - name:
        win_command: cmd.exe /c start google
        
  # - name: Install windows updates
   #  win_updates:
    #   catagory_names:
    #         - CriticalUpdates
   #         - SecurityUpdates
   #          - UpdateRollups
   #    reboot: yes
   #    reboot_timeout: 360
     
     
