# ansible-playbook 

- name : update the phone servers on all clients
  hosts: "*"
  tasks: 
   - name: upgrade the servers
     shell: sudo apt update 
     register: upgrade_output     
     
   - debug: 
         var: upgrade_output.stdout_lines
          
   - name: upgrade the servers
     shell: sudo apt upgrade
     register: reload_output
     
   - debug: 
            var: reload_output.stdout_lines    
   
