# ansible-playbook 

- name : update the servers
  hosts: "*"
  tasks: 
   - name: upgrade the servers
     shell: sudo apt-get update 
     register: upgrade_output     
     
   - debug: 
         var: upgrade_output.stdout_lines
          
   - name: upgrade the servers
     shell: sudo apt-get upgrade -y
     register: reload_output
     
   - debug: 
            var: reload_output.stdout_lines    
   
