# ansible-playbook 

- name : update the servers
  hosts: "*"
  tasks: 
   - name: upgrade the servers
     apt: upgrade=dist force_apt_get=yes 
     register: upgrade_output     
     
   - debug: 
         var: upgrade_output.stdout_lines
          
